# class_mapping.py

class_mapping1 = {
    'tench': 'wildlife',
    'goldfish': 'wildlife',
    'great white shark': 'wildlife',
    'tiger shark': 'wildlife',
    'hammerhead': 'wildlife',
    'electric ray': 'wildlife',
    'stingray': 'wildlife',
    'cock': 'wildlife',
    'hen': 'wildlife',
    'ostrich': 'wildlife',
    'brambling': 'wildlife',
    'goldfinch': 'wildlife',
    'house finch': 'wildlife',
    'junco': 'wildlife',
    'indigo bunting': 'wildlife',
    'robin': 'wildlife',
    'bulbul': 'wildlife',
    'jay': 'wildlife',
    'magpie': 'wildlife',
    'chickadee': 'wildlife',
    'water ouzel': 'wildlife',
    'kite': 'wildlife',
    'bald eagle': 'wildlife',
    'vulture': 'wildlife',
    'great grey owl': 'wildlife',
    'European fire salamander': 'wildlife',
    'common newt': 'wildlife',
    'eft': 'wildlife',
    'spotted salamander': 'wildlife',
    'axolotl': 'wildlife',
    'bullfrog': 'wildlife',
    'tree frog': 'wildlife',
    'tailed frog': 'wildlife',
    'loggerhead': 'wildlife',
    'leatherback turtle': 'wildlife',
    'mud turtle': 'wildlife',
    'terrapin': 'wildlife',
    'box turtle': 'wildlife',
    'banded gecko': 'wildlife',
    'common iguana': 'wildlife',
    'American chameleon': 'wildlife',
    'whiptail': 'wildlife',
    'agama': 'wildlife',
    'frilled lizard': 'wildlife',
    'alligator lizard': 'wildlife',
    'Gila monster': 'wildlife',
    'green lizard': 'wildlife',
    'African chameleon': 'wildlife',
    'Komodo dragon': 'wildlife',
    'African crocodile': 'wildlife',
    'American alligator': 'wildlife',
    'triceratops': 'wildlife',
    'thunder snake': 'wildlife',
    'ringneck snake': 'wildlife',
    'hognose snake': 'wildlife',
    'green snake': 'wildlife',
    'king snake': 'wildlife',
    'garter snake': 'wildlife',
    'water snake': 'wildlife',
    'vine snake': 'wildlife',
    'night snake': 'wildlife',
    'boa constrictor': 'wildlife',
    'rock python': 'wildlife',
    'Indian cobra': 'wildlife',
    'green mamba': 'wildlife',
    'sea snake': 'wildlife',
    'horned viper': 'wildlife',
    'diamondback': 'wildlife',
    'sidewinder': 'wildlife',
    'trilobite': 'wildlife',
    'harvestman': 'insects',
    'scorpion': 'insects',
    'black and gold garden spider': 'insects',
    'barn spider': 'insects',
    'garden spider': 'insects',
    'black widow': 'insects',
    'tarantula': 'insects',
    'wolf spider': 'insects',
    'tick': 'insects',
    'centipede': 'insects',
    'black grouse': 'wildlife',
    'ptarmigan': 'wildlife',
    'ruffed grouse': 'wildlife',
    'prairie chicken': 'wildlife',
    'peacock': 'wildlife',
    'quail': 'wildlife',
    'partridge': 'wildlife',
    'African grey': 'wildlife',
    'macaw': 'wildlife',
    'sulphur-crested cockatoo': 'wildlife',
    'lorikeet': 'wildlife',
    'coucal': 'wildlife',
    'bee eater': 'wildlife',
    'hornbill': 'wildlife',
    'hummingbird': 'wildlife',
    'jacamar': 'wildlife',
    'toucan': 'wildlife',
    'drake': 'wildlife',
    'red-breasted merganser': 'wildlife',
    'goose': 'wildlife',
    'black swan': 'wildlife',
    'tusker': 'wildlife',
    'echidna': 'wildlife',
    'platypus': 'wildlife',
    'wallaby': 'wildlife',
    'koala': 'wildlife',
    'wombat': 'wildlife',
    'jellyfish': 'wildlife',
    'sea anemone': 'wildlife',
    'brain coral': 'wildlife',
    'flatworm': 'wildlife',
    'nematode': 'wildlife',
    'conch': 'wildlife',
    'snail': 'wildlife',
    'slug': 'wildlife',
    'sea slug': 'wildlife',
    'chiton': 'wildlife',
    'chambered nautilus': 'wildlife',
    'Dungeness crab': 'wildlife',
    'rock crab': 'wildlife',
    'fiddler crab': 'wildlife',
    'red rock crab': 'wildlife',
    'American lobster': 'wildlife',
    'spiny lobster': 'wildlife',
    'crayfish': 'wildlife',
    'hermit crab': 'wildlife',
    'isopod': 'wildlife',
    'white stork': 'wildlife',
    'black stork': 'wildlife',
    'spoonbill': 'wildlife',
    'flamingo': 'wildlife',
    'little blue heron': 'wildlife',
    'bittern': 'wildlife',
    'crane': 'wildlife',
    'limpkin': 'wildlife',
    'European gallinule': 'wildlife',
    'American coot': 'wildlife',
    'bustard': 'wildlife',
    'ruddy turnstone': 'wildlife',
    'red-backed sandpiper': 'wildlife',
    'redshank': 'wildlife',
    'dowitcher': 'wildlife',
    'oystercatcher': 'wildlife',
    'pelican': 'wildlife',
    'king penguin': 'wildlife',
    'albatross': 'wildlife',
    'grey whale': 'wildlife',
    'killer whale': 'wildlife',
    'dugong': 'wildlife',
    'sea lion': 'wildlife',
    'Chihuahua': 'pets',
    'Japanese spaniel': 'pets',
    'Maltese dog': 'pets',
    'Pekinese': 'pets',
    'Shih-Tzu': 'pets',
    'Blenheim spaniel': 'pets',
    'papillon': 'pets',
    'toy terrier': 'pets',
    'Rhodesian ridgeback': 'pets',
    'Afghan hound': 'pets',
    'basset': 'pets',
    'beagle': 'pets',
    'bloodhound': 'pets',
    'bluetick': 'pets',
    'black-and-tan coonhound': 'pets',
    'Walker hound': 'pets',
    'English foxhound': 'pets',
    'redbone': 'pets',
    'borzoi': 'pets',
    'Irish wolfhound': 'pets',
    'Italian greyhound': 'pets',
    'whippet': 'pets',
    'Ibizan hound': 'pets',
    'Norwegian elkhound': 'pets',
    'otterhound': 'pets',
    'Saluki': 'pets',
    'Scottish deerhound': 'pets',
    'Weimaraner': 'pets',
    'Staffordshire bullterrier': 'pets',
    'American Staffordshire terrier': 'pets',
    'Bedlington terrier': 'pets',
    'Border terrier': 'pets',
    'Kerry blue terrier': 'pets',
    'Irish terrier': 'pets',
    'Norfolk terrier': 'pets',
    'Norwich terrier': 'pets',
    'Yorkshire terrier': 'pets',
    'wire-haired fox terrier': 'pets',
    'Lakeland terrier': 'pets',
    'Sealyham terrier': 'pets',
    'Airedale': 'pets',
    'cairn': 'pets',
    'Australian terrier': 'pets',
    'Dandie Dinmont': 'pets',
    'Boston bull': 'pets',
    'miniature schnauzer': 'pets',
    'giant schnauzer': 'pets',
    'standard schnauzer': 'pets',
    'Scotch terrier': 'pets',
    'Tibetan terrier': 'pets',
    'silky terrier': 'pets',
    'soft-coated wheaten terrier': 'pets',
    'West Highland white terrier': 'pets',
    'Lhasa': 'pets',
    'flat-coated retriever': 'pets',
    'curly-coated retriever': 'pets',
    'golden retriever': 'pets',
    'Labrador retriever': 'pets',
    'Chesapeake Bay retriever': 'pets',
    'German short-haired pointer': 'pets',
    'vizsla': 'pets',
    'English setter': 'pets',
    'Irish setter': 'pets',
    'Gordon setter': 'pets',
    'Brittany spaniel': 'pets',
    'clumber': 'pets',
    'English springer': 'pets',
    'Welsh springer spaniel': 'pets',
    'cocker spaniel': 'pets',
    'Sussex spaniel': 'pets',
    'Irish water spaniel': 'pets',
    'kuvasz': 'pets',
    'schipperke': 'pets',
    'groenendael': 'pets',
    'malinois': 'pets',
    'briard': 'pets',
    'kelpie': 'pets',
    'komondor': 'pets',
    'Old English sheepdog': 'pets',
    'Shetland sheepdog': 'pets',
    'collie': 'pets',
    'Border collie': 'pets',
    'Bouvier des Flandres': 'pets',
    'Rottweiler': 'pets',
    'German shepherd': 'pets',
    'Doberman': 'pets',
    'miniature pinscher': 'pets',
    'Greater Swiss Mountain dog': 'pets',
    'Bernese mountain dog': 'pets',
    'Appenzeller': 'pets',
    'EntleBucher': 'pets',
    'boxer': 'pets',
    'bull mastiff': 'pets',
    'Tibetan mastiff': 'pets',
    'French bulldog': 'pets',
    'Great Dane': 'pets',
    'Saint Bernard': 'pets',
    'Eskimo dog': 'pets',
    'malamute': 'pets',
    'Siberian husky': 'pets',
    'dalmatian': 'pets',
    'affenpinscher': 'pets',
    'basenji': 'pets',
    'pug': 'pets',
    'Leonberg': 'pets',
    'Newfoundland': 'pets',
    'Great Pyrenees': 'pets',
    'Samoyed': 'pets',
    'Pomeranian': 'pets',
    'chow': 'pets',
    'keeshond': 'pets',
    'Brabancon griffon': 'pets',
    'Pembroke': 'pets',
    'Cardigan': 'pets',
    'toy poodle': 'pets',
    'miniature poodle': 'pets',
    'standard poodle': 'pets',
    'Mexican hairless': 'pets',
    'timber wolf': 'wildlife',
    'white wolf': 'wildlife',
    'red wolf': 'wildlife',
    'coyote': 'wildlife',
    'dingo': 'wildlife',
    'dhole': 'wildlife',
    'African hunting dog': 'wildlife',
    'hyena': 'wildlife',
    'red fox': 'wildlife',
    'kit fox': 'wildlife',
    'Arctic fox': 'wildlife',
    'grey fox': 'wildlife',
    'tabby': 'pets',
    'tiger cat': 'pets',
    'Persian cat': 'pets',
    'Siamese cat': 'pets',
    'Egyptian cat': 'pets',
    'cougar': 'wildlife',
    'lynx': 'wildlife',
    'leopard': 'wildlife',
    'snow leopard': 'wildlife',
    'jaguar': 'wildlife',
    'lion': 'wildlife',
    'tiger': 'wildlife',
    'cheetah': 'wildlife',
    'brown bear': 'wildlife',
    'American black bear': 'wildlife',
    'ice bear': 'wildlife',
    'sloth bear': 'wildlife',
    'mongoose': 'wildlife',
    'meerkat': 'wildlife',
    'tiger beetle': 'insects',
    'ladybug': 'insects',
    'ground beetle': 'insects',
    'long-horned beetle': 'insects',
    'leaf beetle': 'insects',
    'dung beetle': 'insects',
    'rhinoceros beetle': 'insects',
    'weevil': 'insects',
    'fly': 'insects',
    'bee': 'insects',
    'ant': 'insects',
    'grasshopper': 'insects',
    'cricket': 'insects',
    'walking stick': 'insects',
    'cockroach': 'insects',
    'mantis': 'insects',
    'cicada': 'insects',
    'leafhopper': 'insects',
    'lacewing': 'insects',
    'dragonfly': 'insects',
    'damselfly': 'insects',
    'admiral': 'insects',
    'ringlet': 'insects',
    'monarch': 'insects',
    'cabbage butterfly': 'insects',
    'sulphur butterfly': 'insects',
    'lycaenid': 'insects',
    'starfish': 'wildlife',
    'sea urchin': 'wildlife',
    'sea cucumber': 'wildlife',
    'wood rabbit': 'wildlife',
    'hare': 'wildlife',
    'Angora': 'wildlife',
    'hamster': 'wildlife',
    'porcupine': 'wildlife',
    'fox squirrel': 'wildlife',
    'marmot': 'wildlife',
    'beaver': 'wildlife',
    'guinea pig': 'wildlife',
    'sorrel': 'wildlife',
    'zebra': 'wildlife',
    'hog': 'wildlife',
    'wild boar': 'wildlife',
    'warthog': 'wildlife',
    'hippopotamus': 'wildlife',
    'ox': 'wildlife',
    'water buffalo': 'wildlife',
    'bison': 'wildlife',
    'ram': 'wildlife',
    'bighorn': 'wildlife',
    'ibex': 'wildlife',
    'hartebeest': 'wildlife',
    'impala': 'wildlife',
    'gazelle': 'wildlife',
    'Arabian camel': 'wildlife',
    'llama': 'wildlife',
    'weasel': 'wildlife',
    'mink': 'wildlife',
    'polecat': 'wildlife',
    'black-footed ferret': 'wildlife',
    'otter': 'wildlife',
    'skunk': 'wildlife',
    'badger': 'wildlife',
    'armadillo': 'wildlife',
    'three-toed sloth': 'wildlife',
    'orangutan': 'wildlife',
    'gorilla': 'wildlife',
    'chimpanzee': 'wildlife',
    'gibbon': 'wildlife',
    'siamang': 'wildlife',
    'guenon': 'wildlife',
    'patas': 'wildlife',
    'baboon': 'wildlife',
    'macaque': 'wildlife',
    'langur': 'wildlife',
    'colobus': 'wildlife',
    'proboscis monkey': 'wildlife',
    'marmoset': 'wildlife',
    'capuchin': 'wildlife',
    'howler monkey': 'wildlife',
    'titi': 'wildlife',
    'spider monkey': 'wildlife',
    'squirrel monkey': 'wildlife',
    'Madagascar cat': 'wildlife',
    'indri': 'wildlife',
    'Indian elephant': 'wildlife',
    'African elephant': 'wildlife',
    'lesser panda': 'wildlife',
    'giant panda': 'wildlife',
    'barracouta': 'wildlife',
    'eel': 'wildlife',
    'coho': 'wildlife',
    'rock beauty': 'wildlife',
    'anemone fish': 'wildlife',
    'sturgeon': 'wildlife',
    'gar': 'wildlife',
    'lionfish': 'wildlife',
    'puffer': 'wildlife',
    'abacus': 'technology',
    'abaya': 'clothes',
    'academic gown': 'clothes',
    'accordion': 'music',
    'acoustic guitar': 'music',
    'aircraft carrier': 'infrastructure',
    'airliner': 'infrastructure',
    'airship': 'infrastructure',
    'altar': 'infrastructure',
    'ambulance': 'infrastructure',
    'amphibian': 'wildlife',
    'analog clock': 'technology',
    'apiary': 'wildlife',
    'apron': 'clothes',
    'ashcan': 'recycling bin',
    'assault rifle': 'technology',
    'ice cream': 'food',
    'ice lolly': 'food',
    'ice pop': 'food',
    'ice-cream': 'food',
    'ironing board': 'furniture',
    'iron': 'technology',
    'isopod': 'insects',
    'jack-o-lantern': 'celebration',
    'jean': 'clothes',
    'jeans': 'clothes',
    'jersey': 'clothes',
    'jigsaw puzzle': 'game',
    'jigsaw': 'tools',
    'jinrikisha': 'infrastructure',
    'joystick': 'technology',
    'kimono': 'clothes',
    'knee pad': 'fashion',
    'knot': 'tools',
    'lab coat': 'clothes',
    'ladle': 'kitchenware',
    'lampshade': 'lighting',
    'laptop': 'technology',
    'lawn mower': 'garden',
    'lens cap': 'technology',
    'letter opener': 'stationery',
    'library': 'building',
    'lifeboat': 'marine',
    'lighter': 'kitchenware',
    'limousine': 'infrastructure',
    'liner': 'infrastructure',
    'lipstick': 'fashion',
    'llama': 'wildlife',
    'lock': 'tools',
    'lotion': 'fashion',
    'loudspeaker': 'technology',
    'loupe': 'technology',
    'lumbermill': 'infrastructure',
    'magnetic compass': 'navigation',
    'mailbag': 'stationery',
    'mailbox': 'infrastructure',
    'maillot': 'clothes',
    'maillot,': 'clothes',
    'manhole cover': 'infrastructure',
    'map': 'navigation',
    'maraca': 'music',
    'marimba': 'music',
    'mask': 'fashion',
    'matchstick': 'kitchenware',
    'maypole': 'celebration',
    'maze': 'infrastructure',
    'measuring cup': 'kitchenware',
    'measuring cup,': 'kitchenware',
    'medicine chest': 'furniture',
    'merry-go-round': 'playing sports',
    'milk can': 'kitchenware',
    'minibus': 'infrastructure',
    'miniskirt': 'clothes',
    'missile': 'technology',
    'mitten': 'clothes',
    'mixing bowl': 'kitchenware',
    'mobile home': 'building',
    'modem': 'technology',
    'monastery': 'building',
    'monitor': 'technology',
    'moped': 'infrastructure',
    'mortar': 'kitchenware',
    'mortarboard': 'fashion',
    'mosque': 'building',
    'mosquito net': 'insects',
    'motor scooter': 'infrastructure',
    'mountain bike': 'bicycle',
    'mountain tent': 'camping',
    'mouse': 'pets',
    'mousetrap': 'tools',
    'moving van': 'infrastructure',
    'muzzle': 'tools',
    'nail': 'tools',
    'neck brace': 'health',
    'necklace': 'fashion',
    'nipple': 'health',
    'notebook': 'mental health',
    'obelisk': 'infrastructure',
    'oboe': 'music',
    'ocarina': 'music',
    'odometer': 'technology',
    'oil filter': 'technology',
    'organ': 'music',
    'oscilloscope': 'technology',
    'overskirt': 'clothes',
    'ox': 'wildlife',
    'oxygen mask': 'health',
    'packet': 'recycling bin',
    'paddle': 'tools',
    'paddlewheel': 'infrastructure',
    'padlock': 'infrastructure',
    'paintbrush': 'art',
    'pajamas': 'clothes',
    'palace': 'building',
    'panpipe': 'music',
    'paper towel': 'kitchenware',
    'parachute': 'technology',
    'parallel bars': 'playing sports',
    'park bench': 'park',
    'parking meter': 'infrastructure',
    'passenger car': 'infrastructure',
    'patio': 'building',
    'pay-phone': 'technology',
    'pedestal': 'infrastructure',
    'pencil box': 'stationery',
    'pencil sharpener': 'stationery',
    'perfume': 'fashion',
    'petri dish': 'science',
    'photocopier': 'technology',
    'pick': 'tools',
    'pickelhaube': 'clothes',
    'picket fence': 'infrastructure',
    'pickup': 'infrastructure',
    'pier': 'infrastructure',
    'piggy bank': 'finance',
    'pill bottle': 'health',
    'pillow': 'furniture',
    'ping-pong ball': 'playing sports',
    'pinwheel': 'toys',
    'pirate': 'costume',
    'pitcher': 'kitchenware',
    'plane': 'tools',
    'planetarium': 'building',
    'plastic bag': 'recycling bin',
    'plate rack': 'kitchenware',
    'plow': 'tools',
    'plunger': 'tools',
    'polaroid camera': 'technology',
    'pole': 'infrastructure',
    'police van': 'infrastructure',
    'poncho': 'clothes',
    'pool table': 'playing sports',
    'pop bottle': 'recycling bin',
    'pot': 'kitchenware',
    'potter\'s wheel': 'art',
    'power drill': 'tools',
    'prayer rug': 'furniture',
    'printer': 'technology',
    'prison': 'infrastructure',
    'projectile': 'technology',
    'projector': 'technology',
    'puck': 'playing sports',
    'punching bag': 'playing sports',
    'purse': 'fashion',
    'quill': 'writing',
    'quilt': 'furniture',
    'racer': 'bicycle',
    'radiator': 'technology',
    'radio': 'technology',
    'radio telescope': 'science',
    'rain barrel': 'recycling bin',
    'recreational vehicle': 'infrastructure',
    'reel': 'tools',
    'reflex camera': 'technology',
    'refrigerator': 'technology',
    'remote control': 'technology',
    'restaurant': 'eating out',
    'revolver': 'tools',
    'rifle': 'tools',
    'rocking chair': 'furniture',
    'rotisserie': 'kitchenware',
    'rubber eraser': 'stationery',
    'rugby ball': 'playing sports',
    'rule': 'tools',
    'running shoe': 'clothes',
    'safe': 'tools',
    'safety pin': 'tools',
    'saltshaker': 'kitchenware',
    'sandal': 'clothes',
    'sarong': 'clothes',
    'sax': 'music',
    'scabbard': 'tools',
    'scale': 'technology',
    'school bus': 'infrastructure',
    'schooner': 'infrastructure',
    'scoreboard': 'playing sports',
    'screen': 'technology',
    'screw': 'tools',
    'screwdriver': 'tools',
    'seat belt': 'infrastructure',
    'sewing machine': 'technology',
    'shield': 'tools',
    'shoe shop': 'building',
    'shoji': 'building',
    'shopping basket': 'infrastructure',
    'shopping cart': 'infrastructure',
    'shovel': 'tools',
    'shower cap': 'fashion',
    'shower curtain': 'furniture',
    'ski': 'playing sports',
    'ski mask': 'fashion',
    'sleeping bag': 'camping',
    'slide rule': 'science',
    'sliding door': 'building',
    'slot': 'game',
    'snorkel': 'playing sports',
    'snowmobile': 'infrastructure',
    'snowplow': 'infrastructure',
    'soap dispenser': 'kitchenware',
    'soccer ball': 'playing sports',
    'sock': 'clothes',
    'solar dish': 'solar panel',
    'sombrero': 'clothes',
    'soup bowl': 'kitchenware',
    'space bar': 'technology',
    'space heater': 'technology',
    'space shuttle': 'infrastructure',
    'spatula': 'kitchenware',
    'speedboat': 'marine',
    'spider web': 'insects',
    'spindle': 'tools',
    'sports car': 'infrastructure',
    'spotlight': 'lighting',
    'stage': 'art',
    'steam locomotive': 'infrastructure',
    'steel arch bridge': 'infrastructure',
    'steel drum': 'music',
    'stethoscope': 'health',
    'stole': 'clothes',
    'stone wall': 'infrastructure',
    'stopwatch': 'technology',
    'stove': 'kitchenware',
    'strainer': 'kitchenware',
    'streetcar': 'infrastructure',
    'stretcher': 'health',
    'studio couch': 'furniture',
    'stupa': 'infrastructure',
    'submarine': 'infrastructure',
    'suit': 'clothes',
    'sundial': 'infrastructure',
    'sunglass': 'fashion',
    'sunglasses': 'fashion',
    'sunscreen': 'health',
    'suspension bridge': 'infrastructure',
    'swab': 'health',
    'sweatshirt': 'clothes',
    'swimming trunks': 'clothes',
    'swing': 'playing sports',
    'switch': 'technology',
    'syringe': 'health',
    'table lamp': 'furniture',
    'tank': 'infrastructure',
    'tape player': 'technology',
    'teapot': 'kitchenware',
    'teddy': 'toys',
    'television': 'technology',
    'tennis ball': 'playing sports',
    'thatch': 'infrastructure',
    'theater': 'building',
    'thimble': 'tools',
    'thresher': 'tools',
    'throne': 'furniture',
    'tile roof': 'building',
    'toaster': 'kitchenware',
    'tobacco shop': 'building',
    'toilet seat': 'health',
    'torch': 'lighting',
    'totem pole': 'art',
    'tow truck': 'infrastructure',
    'toyshop': 'building',
    'tractor': 'tools',
    'trailer truck': 'infrastructure',
    'tray': 'kitchenware',
    'trench coat': 'clothes',
    'tricycle': 'bicycle',
    'trimaran': 'infrastructure',
    'tripod': 'tools',
    'triumphal arch': 'infrastructure',
    'trolleybus': 'infrastructure',
    'trombone': 'music',
    'tub': 'health',
    'turnstile': 'infrastructure',
    'typewriter keyboard': 'technology',
    'umbrella': 'fashion',
    'unicycle': 'bicycle',
    'upright': 'furniture',
    'vacuum': 'technology',
    'vase': 'furniture',
    'vault': 'infrastructure',
    'velvet': 'fashion',
    'vending machine': 'technology',
    'vestment': 'clothes',
    'viaduct': 'infrastructure',
    'violin': 'music',
    'volleyball': 'playing sports',
    'waffle iron': 'kitchenware',
    'wall clock': 'technology',
    'wallet': 'fashion',
    'wardrobe': 'furniture',
    'warplane': 'infrastructure',
    'washbasin': 'health',
    'washer': 'technology',
    'water bottle': 'kitchenware',
    'water jug': 'kitchenware',
    'water tower': 'infrastructure',
    'whiskey jug': 'kitchenware',
    'whistle': 'tools',
    'wig': 'fashion',
    'window screen': 'building',
    'window shade': 'furniture',
    'Windsor tie': 'clothes',
    'wine bottle': 'kitchenware',
    'wing': 'infrastructure',
    'wok': 'kitchenware',
    'wooden spoon': 'kitchenware',
    'wool': 'material',
    'worm fence': 'infrastructure',
    'wreck': 'infrastructure',
    'yawl': 'infrastructure',
    'yurt': 'building',
    'web site': 'technology',
    'comic book': 'mental health',
    'crossword puzzle': 'game',
    'street sign': 'infrastructure',
    'traffic light': 'infrastructure',
    'book jacket': 'writing',
    'menu': 'food',
    'plate': 'kitchenware',
    'guacamole': 'food',
    'consomme': 'food',
    'hot pot': 'food',
    'trifle': 'food',
    'ice cream': 'food',
    'ice lolly': 'food',
    'French loaf': 'food',
    'bagel': 'food',
    'pretzel': 'food',
    'cheeseburger': 'food',
    'hotdog': 'food',
    'mashed potato': 'food',
    'cabbage': 'food',
    'broccoli': 'food',
    'cauliflower': 'food',
    'zucchini': 'food',
    'spaghetti squash': 'food',
    'acorn squash': 'food',
    'butternut squash': 'food',
    'cucumber': 'food',
    'artichoke': 'food',
    'bell pepper': 'food',
    'cardoon': 'food',
    'mushroom': 'food',
    'Granny Smith': 'food',
    'strawberry': 'food',
    'orange': 'food',
    'lemon': 'food',
    'fig': 'food',
    'pineapple': 'food',
    'banana': 'food',
    'jackfruit': 'food',
    'custard apple': 'food',
    'pomegranate': 'food',
    'hay': 'material',
    'carbonara': 'food',
    'chocolate sauce': 'food',
    'dough': 'food',
    'meat loaf': 'food',
    'pizza': 'food',
    'potpie': 'food',
    'burrito': 'food',
    'red wine': 'food',
    'espresso': 'food',
    'cup': 'kitchenware',
    'eggnog': 'food',
    'alp': 'landscape',
    'bubble': 'nature',
    'cliff': 'landscape',
    'coral reef': 'ocean',
    'geyser': 'nature',
    'lakeside': 'nature',
    'promontory': 'landscape',
    'sandbar': 'beach',
    'seashore': 'beach',
    'valley': 'landscape',
    'volcano': 'landscape',
    'ballplayer': 'playing sports',
    'groom': 'people',
    'scuba diver': 'playing sports',
    'rapeseed': 'plant',
    'daisy': 'flower',
    'yellow lady\'s slipper': 'flower',
    'corn': 'plant',
    'acorn': 'plant',
    'hip': 'plant',
    'buckeye': 'plant',
    'coral fungus': 'fungi',
    'agaric': 'fungi',
    'gyromitra': 'fungi',
    'stinkhorn': 'fungi',
    'earthstar': 'fungi',
    'hen-of-the-woods': 'fungi',
    'bolete': 'fungi',
    'ear': 'body parts',
    'toilet tissue': 'kitchenware',
    'limousine': 'infrastructure',
    'taxicab': 'infrastructure',
    'seat belt': 'infrastructure',
    'go-kart': 'playing sports',
    'T-shirt': 'clothes',
    'burrito': 'food',
    'hot pot': 'food',
    'consomme': 'food',
    'pot pie': 'food',
    'ring binder': 'stationery',
    'hard disk drive': 'technology',
    'Norwalk Terrier': 'pets',
    'Border Terrier': 'pets',
    'Norfolk Terrier': 'pets',
    'Australian Silky Terrier': 'pets',
    'marimba': 'music',
    'binoculars': 'tools',
    'honeycomb': 'wildlife',
    'buckle': 'tools',
    'shopping basket': 'infrastructure',
    'race car': 'infrastructure',
    'eraser': 'stationery',
    'ruler': 'stationery',
    'pencil case': 'stationery',
    'swing': 'playing sports', 
    'Dutch oven': 'kitchenware',
    'cauldron': 'kitchenware',
    'palace': 'building',
    'castle': 'building',
    'pier': 'infrastructure',
    'dam': 'infrastructure',
    'paddle': 'playing sports',
    'canoe': 'playing sports',
    'church': 'building',
    'menu': 'eating out',
    'tray': 'kitchenware',
    'envelope': 'stationery',
    'pillow': 'furniture',
    'dust jacket': 'clothes',
    'shopping basket': 'infrastructure',
    'hamper': 'recycling bin',
    'crossword': 'games',
    'packet': 'recycling bin',
    'potter\'s wheel': 'art',
    'rain barrel': 'gardening',
    'beer glass': 'kitchenware',
    'goblet': 'kitchenware',
    'mosquito net': 'health',
    'four-poster bed': 'furniture',
    'consomme': 'food',
    'brass': 'material',
    'bulletproof vest': 'safety',
    'fur coat': 'clothes',
    'trench coat': 'clothes',
    'West Highland White Terrier': 'pets',
    'Siberian Husky': 'pets',
    'candle': 'household',
    'plate': 'kitchenware',
    'waffle iron': 'kitchenware',
    'weighing scale': 'health',
    'parallel bars': 'playing sports',
    'swing': 'playing sports',
    'hair dryer': 'technology',
    'space shuttle': 'technology',
    'jackfruit': 'food',
    'bolete': 'food',
    'quill': 'stationery',
    'handkerchief': 'fashion',
    'square academic cap': 'education',
    'academic gown': 'education',
    'website': 'information',
    'lakeshore': 'nature',
    'harvester': 'agriculture',
    'shoal': 'marine',
    'breakwater': 'infrastructure',
    'tent': 'camping',
    'boathouse': 'marine',
    'fountain': 'infrastructure',
    'split-rail fence': 'agriculture',
    'grocery store': 'food',
    'bookstore': 'mental health',
    'fire screen sheet': 'safety',
    'bakery': 'food',
    'baguette': 'food',
    'bookcase': 'furniture',
    'dining table': 'furniture',
    'confectionery store': 'food',
    'crate': 'logistics',
    'barbell': 'fitness',
    'can opener': 'kitchenware',
    'desk': 'furniture',
    'Sussex Spaniel': 'pets',
    'solar thermal collector': 'energy',
    'bra': 'clothing',
    'sink': 'household',
    'microwave oven': 'household',
    'couch': 'furniture',
    'baluster': 'construction',
    'china cabinet': 'furniture',
    'entertainment center': 'furniture',
    'automated teller machine': 'technology', 
    'home theater': 'technology',
    'balance beam': 'playing sports',
    'greenhouse': 'gardening',
    'folding chair': 'furniture',
    'chest': 'furniture',
    'filing cabinet': 'office supplies',
    'chiffonier': 'furniture',
    'traffic sign': 'infrastructure',
    'doormat': 'household',
    'ear of corn': 'food',
    'payphone': 'technology',
    'bottle cap': 'recycling',
    'harmonica': 'music',
    'vacuum cleaner': 'technology',
    'earth star': 'plants',
    'barrette': 'fashion',
    'cowboy hat': 'fashion',
    'crane (machine)': 'construction',
    'Band-Aid': 'health',
    'bell-cot': 'architecture',
    'pulled rickshaw': 'transportation',
    'car mirror': 'automotive',
    'drumstick': 'music',
    'plectrum': 'music',
    'coffeemaker': 'kitchenware',
    'stick insect': 'wildlife',
    'Gordon Setter': 'pets',
    'thatched roof': 'construction',
    'beaker': 'laboratory equipment',
    'hot dog': 'food',
    'gown': 'fashion',
    'barber chair': 'furniture',
    'lighthouse': 'infrastructure',
    'bridegroom': 'fashion',
    'match': 'household',
    'catamaran': 'transportation',
    'croquet ball': 'playing sports',
    'wheelchair': 'health',
    'tandem bicycle': 'transportation',
    'bow': 'playing sports',
    'swimming cap': 'playing sports',
    'coil': 'technology',
    'face powder': 'cosmetics',
    'grey parrot': 'pets',
    'mobile phone': 'technology',
    'waste container': 'recycling',
    'cloak': 'fashion',
    'hoog skirt': 'fashion',
    'hand-held computer': 'technology',
    'carton': 'packaging',
    'golf cart': 'transportation',
    'chainsaw': 'tools'
}